branch-defaults:
  master:
    environment: Backend-env
deploy:
  artifact: www/Archive.zip
environment-defaults:
  Backend-env:
    branch: null
    repository: null
global:
  application_name: backend
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
