version: 2.1

orbs:
  node: circleci/node@4.1
  browser-tools: circleci/browser-tools@1.1.3
  aws-cli: circleci/aws-cli@1.3.1
  aws-eb: circleci/aws-elastic-beanstalk@1.0.2

jobs:
  deploy:  
    docker:
      - image: cimg/node:15.0.1-browsers
    steps:
      - checkout
      - node/install
      - browser-tools/install-chrome
      - aws-cli/setup
      - aws-eb/setup
      - run:
          name: Deploy Front-end 
          command: npm run deploy:front
      - run:
          name: Deploy Back-end
          command: npm run deploy:back
    

workflows:
  udagram:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master