version: 2.1

orbs:
  node: circleci/node@4.1
  browser-tools: circleci/browser-tools@1.1.3
  aws-cli: circleci/aws-cli@1.3.1
  aws-eb: circleci/aws-elastic-beanstalk@1.0.2

jobs:
  deploy:
    docker:
      - image: cimg/node:15.0.1-browsers
    steps:
      - checkout
      - node/install
      - browser-tools/install-chrome
      - aws-cli/setup
      - aws-eb/setup
      - run:
          name: Install Front-end packages
          command: npm run install:front
      - run:
          name: Test Front-end
          command: npm run test:front
      - run:
          name: build Front-end
          command: npm run build:front
      - run:
          name: Install Back-end
          command: npm run install:back
      - run:
          name: Test Back-end
          command: npm run test:back
      - run:
          name: Build Back-end
          command: npm run build:back
      - run:
          name: Deploy Back-end
          command: npm run deploy:back
      - run:
          name: Deploy Front-end
          command: npm run deploy:front

workflows:
  udagram:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
