echo 'echo $AWS_BUCKET'
echo $AWS_BUCKET
echo 'echo $AWS_REGION'
echo $AWS_REGION
echo 'echo $JWT_SECRET'
echo $JWT_SECRET
echo 'echo $PORT'
echo $PORT
echo 'echo $POSTGRES_DB'
echo $POSTGRES_DB
echo 'echo $POSTGRES_HOST'
echo $POSTGRES_HOST
echo 'echo $POSTGRES_PASSWORD'
echo $POSTGRES_PASSWORD
echo 'echo $POSTGRES_USERNAME'
echo $POSTGRES_USERNAME
echo 'echo $URL'
echo $URL

eb deploy --profile default
eb setenv AWS_BUCKET=$AWS_BUCKET AWS_REGION=$AWS_REGION JWT_SECRET=$JWT_SECRET PORT=$PORT POSTGRES_DB=$POSTGRES_DB POSTGRES_HOST=$POSTGRES_HOST POSTGRES_PASSWORD=$POSTGRES_PASSWORD POSTGRES_USERNAME=$POSTGRES_USERNAME URL=$URL --profile default

